### ISSUE TITLE
Ripple doesn't follow element

### ISSUE THREAD

**Issue by thegifter** [PygmySlowLoris/vue-ripple-directive#11] opened 2017-08-02 21:23 UTC
When using this, the ripple effect doesn't follow the element if the element is moving on the page. Example :  Use this on a navbar that is fixed to the top view. When clicking a nav link, the ripple plays, but not relative to the button, only relative to the page. When clicking the nav button, the page scrolls down, and the ripple animation stays attached to the page as  it scrolls out of view...

**Comment by hazzo** [comment] 2017-10-04 08:57
Hi @thegifter sorry for the delay.

We have changed the ripple to solve this bug. 

It has a **breaking change** which involves having your target with `position: relative`. If the target does not have it there is no big issue because the directive adds the relative position to the target.

But if previously it had another position the directive will restore it after the ripple is cleared out. This will break obviously targets that are fixed or absolute, because they will be forced to relative. Although later their original position will be added again, there will be a weird effect when changing positions. 

Because of that it's almost *obligatory* that the target it's relative positioned. 

Actually this version it's only on beta so you and others can test it. So if works right will publish it as stable.

Please use: `"vue-ripple-directive": "^2.0.0-beta"` 
Or: `npm install vue-ripple-directive@beta --save`

Thanks for reporting!
We are looking forward to know again from you with some feedback.

**Comment by hackuun** [comment] 2017-10-24 20:43
I can confirm, I have the same issue, but with page transitions. When I click the button ripple effect continue even after I navigate to other page.

**Comment by hazzo** [comment] 2017-10-24 20:45
@iamdubx please can you test beta?

npm install vue-ripple-directive@beta --save

If you confirm that this issue is solved in the beta version will upgrade to stable.

Thanks for reporting!

**Comment by hackuun** [comment] 2017-10-24 20:45
@hazzo just tried `2.0.0-beta`. Looks like it fix this behavior, but other bug appear 

![button](https://user-images.githubusercontent.com/30086515/31967069-be2b466c-b8da-11e7-90a4-e03b855a5286.png)

**Comment by hackuun** [comment] 2017-10-24 20:48
For some reason ripple effect doesn't centered in element in `2.0.0`. I have no styles. With previous version it was centered.

**Comment by hazzo** [comment] 2017-10-24 20:50
Okey cool, thanks for testing. I'll take a look and let you know as soon as possible.

**Comment by luiztsmelo** [comment] 2017-11-14 12:17
I think the root of this problem is the performance. The ripple takes about 100ms to appear, right? There's a way to improve it?

**Comment by hazzo** [comment] 2017-11-30 12:09
Hi and sorry for the delay again :disappointed: 

@iamdubx I manage to reproduce your error, and the problem seems to be related to the  tag `<button>` and its computed styles (border, border inset, etc). I managed to fix it with a temporary solution by checking if element has border and re position the ripple in relation to this styles (*I must warn that it's not PERFECT*). It seems that they create some kind of offset on absolute positioned elements with relative parents.

I published another beta version, could you please see if it kind of solves your issue?
`npm install vue-ripple-directive@2.0.1-beta`
`"vue-ripple-directive": "^2.0.1-beta"` 

Thanks again!

If no mayor issues appear I will consider publishing a final release because ripple should meant to be absolute positioned to its parent relative position.

**Comment by hackuun** [comment] 2017-11-30 13:26
@hazzo I checked `2.0.1` seems like issue is fixed. Thanks!

**Comment by hazzo** [comment] 2017-11-30 13:53
@iamdubx cool! Thanks for testing it. I'll publish version 2 later.

**Comment by hazzo** [comment] 2017-11-30 15:37
@iamdubx @luiztsmelo the directive is now on version 2.0.1 with this issue fixed. Closing the issue.

Thanks for the feedback to you all.

**Closed as completed by hazzo** 2017-11-30 15:37 UTC
Labels: bug
